### ISSUE TITLE
Use `platformdirs` to determine the user config directory

### ISSUE THREAD

**Issue by mportesdev** [EndlessTrax/kachi#22]
The third-party library `platformdirs` could be used to determine the user config directory.

https://platformdirs.readthedocs.io

For example on Linux, this gives the same path as the current implementation:

```
>>> import pathlib
>>> pathlib.Path.home() / ".config" / "kachi" / "config.yaml"
PosixPath('/home/michal/.config/kachi/config.yaml')
```

```
>>> import platformdirs
>>> platformdirs.user_config_path(appname="kachi") / "config.yaml"
PosixPath('/home/michal/.config/kachi/config.yaml')
```

But it may differ on other platforms.

**Comment by EndlessTrax** [comment]
Hi @mportesdev,

Thank you for opening the issue. I'm always happy to learn about new python libraries. 

However, I don't think importing a complete library of code and its dependencies for a one-line change is a good enough trade off at present. If more uses cases for `platformdirs` become available in this library as it develops, I may decide to incorporate it in the future.

Thank you for taking the time to look `kachi`.
